#!/usr/bin/env node
// Static site generator, replacing `gatsby build`. Renders every page in
// src/lib/routes.js to dist/<route>/index.html, inlines the CSS, emits the
// sitemap and 404.html, generates the client scripts, and copies static/.
// See docs/simplification-plan.md, Phase 1.
import * as esbuild from 'esbuild'
import { cp, mkdir, readFile, readdir, rm, stat, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'

const root = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const dist = path.join(root, 'dist');
const cache = path.join(root, '.cache'); // gitignored; may hold stale Gatsby output
const ssr = path.join(cache, 'ssg');

// what ships to browsers (client JS + CSS); explicit so syntax lowering and
// CSS prefixing (e.g. -webkit-sticky for Safari <= 12) are a choice, not an
// accident of esbuild's defaults
const BROWSER_TARGET = ['chrome80', 'edge80', 'firefox75', 'safari12'];

// Share cards are generated by scripts/make-og.mjs and committed (Netlify has
// no rsvg-convert), so this build only copies them -- which means the size gate
// has to be re-applied here or a hand-edited or stale oversized card ships
// unnoticed. Over ~300 KB, iMessage/WhatsApp/Slack quietly skip the image and
// the link previews as a grey box, with nothing in any log to say so. Keep in
// sync with MAX_BYTES in scripts/make-og.mjs.
const OG_MAX_BYTES = 250_000;

async function check_og_cards(dir){
    const cards = (await readdir(dir)).filter(f => f.endsWith('.png'));
    if (cards.length === 0){
        throw new Error(`no share cards in ${dir}: run \`npm run og\``);
    }
    for (const card of cards){
        const { size } = await stat(path.join(dir, card));
        if (size > OG_MAX_BYTES){
            throw new Error(`og/${card} is ${size} bytes (> ${OG_MAX_BYTES}); `
                + 'rerun `npm run og` or simplify the card layout');
        }
    }
    return cards.length;
}

// Everything a browser needs to install the site, derived from the manifest so
// there is one source of truth for the values -- but repeated as <meta> tags
// because iOS ignores the manifest entirely.
//
// iOS wants exactly ONE apple-touch-icon, at 180x180. This used to emit a link
// for every icon in the manifest, and every one of those icons had a
// transparent background -- which iOS composites against *black*, so the home
// screen showed the wheel on a black tile.
function app_meta(manifest){
    const required = ['name', 'short_name', 'start_url', 'display',
                      'theme_color', 'background_color'];
    for (const field of required){
        if (!manifest[field]) throw new Error(`manifest is missing ${field}`);
    }
    // checked before it is walked: an absent icons array would otherwise fail
    // with a TypeError instead of something that says what to do about it
    if (!Array.isArray(manifest.icons) || manifest.icons.length === 0){
        throw new Error('manifest lists no icons: run `npm run icons`');
    }
    if (!manifest.icons.some(i => i.purpose === 'maskable')){
        // without one, Android crops the artwork to its launcher shape and
        // clips the wheel's rim; see scripts/make-icons.mjs
        throw new Error('manifest has no maskable icon: run `npm run icons`');
    }
    const touch = manifest.icons.find(i => i.sizes === '180x180' && i.purpose !== 'maskable');
    if (!touch) throw new Error('manifest has no 180x180 icon for apple-touch-icon');

    return `<meta name="theme-color" content="${xml_escape(manifest.theme_color)}"/>`
        + '<meta name="mobile-web-app-capable" content="yes"/>'
        // the apple- prefix is deprecated in favour of the line above, but
        // older iOS still reads only this one
        + '<meta name="apple-mobile-web-app-capable" content="yes"/>'
        + `<meta name="apple-mobile-web-app-title" content="${xml_escape(manifest.name)}"/>`
        + `<link rel="apple-touch-icon" sizes="${touch.sizes}" href="${touch.src}"/>`;
}

function xml_escape(s){
    return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
            .replace(/"/g, '&quot;').replace(/'/g, '&apos;');
}

// JSON that is safe to embed in a script regardless of context
function script_json(value){
    return JSON.stringify(value).replace(/</g, '\\u003c');
}

// pwa.md Phase 4: hosted GoatCounter, cookie-free and consent-banner-free.
// `async` and last in the body, so it is fetched after the page has parsed and
// after the site's own scripts have run -- analytics never sits on the critical
// path, and a slow or unreachable gc.zgo.at delays nothing.
//
// count.js declines to count from localhost and from file:// on its own, so
// `npm run serve` and a build opened off disk stay out of the dashboard without
// a build-time switch here. Netlify deploy previews do NOT get that for free:
// they are a real host, and their hits land in the same dashboard as
// production's. Visiting any page with #toggle-goatcounter turns counting off
// for that browser (GoatCounter stores a flag in localStorage), which is the
// intended fix for both preview traffic and Jason's own visits.
function analytics_tag(endpoint, src){
    return `<script data-goatcounter="${xml_escape(endpoint)}" async src="${xml_escape(src)}"></script>`;
}

function page_html({ head, body, scripts }, css, app, analytics){
    return '<!DOCTYPE html><html lang="en"><head>'
        + '<meta charset="utf-8"/>'
        + '<meta http-equiv="x-ua-compatible" content="ie=edge"/>'
        // viewport-fit=cover lets the page paint into the notch/home-indicator
        // area; it only works paired with the env(safe-area-inset-*) padding on
        // .container in layout.module.css -- one without the other either clips
        // content under the notch or wastes the inset.
        + '<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no, viewport-fit=cover"/>'
        // the site is light-only until pwa.md Phase 6 decides on dark mode.
        // Saying so stops the browser from painting a dark canvas behind a
        // light page (a white flash, or worse, dark form controls on it).
        + '<meta name="color-scheme" content="light"/>'
        + head
        + `<style>${css}</style>`
        + '<link rel="icon" href="/favicon-32x32.png" type="image/png"/>'
        + '<link rel="manifest" href="/manifest.webmanifest" crossorigin="anonymous"/>'
        + app
        + '<link rel="sitemap" type="application/xml" href="/sitemap/sitemap-index.xml"/>'
        + '</head><body>'
        + body
        + (scripts || '')
        + analytics
        + '</body></html>';
}

function sitemap_xml(site_url, paths){
    const urls = paths.map(p =>
        `<url><loc>${xml_escape(site_url + p)}</loc><changefreq>daily</changefreq><priority>0.7</priority></url>`
    ).join('');
    return {
        'sitemap-index.xml': '<?xml version="1.0" encoding="UTF-8"?>'
            + '<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'
            + `<sitemap><loc>${xml_escape(site_url)}/sitemap/sitemap-0.xml</loc></sitemap>`
            + '</sitemapindex>',
        'sitemap-0.xml': '<?xml version="1.0" encoding="UTF-8"?>'
            + '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'
            + urls
            + '</urlset>',
    };
}

async function build(){
    await rm(dist, { recursive: true, force: true });
    await rm(cache, { recursive: true, force: true });

    // install metadata + the apple-touch-icon link, derived from the manifest
    // so there is one source of truth for the icon set and the theme colour
    const manifest = JSON.parse(await readFile(path.join(root, 'static', 'manifest.webmanifest'), 'utf8'));
    const app = app_meta(manifest);

    // 1. Bundle the SSR entry (JSX + CSS modules + data.json) for Node.
    await esbuild.build({
        entryPoints: [path.join(root, 'scripts', 'render.js')],
        bundle: true,
        platform: 'node',
        format: 'esm',
        packages: 'external', // react/react-dom resolve from node_modules
        loader: { '.js': 'jsx' },
        target: 'node22', // the engines floor, not .nvmrc: this must run
                          // on the oldest Node we claim to support
        outdir: ssr,
        outExtension: { '.js': '.mjs' },
    });

    const { CLASS_NAMES, GC_ENDPOINT, GC_PLAY_EVENT, GC_SCRIPT, SITE_TITLE, SITE_URL,
            random_targets, render_pages } =
        await import(pathToFileURL(path.join(ssr, 'render.mjs')));

    const analytics = analytics_tag(GC_ENDPOINT, GC_SCRIPT);

    // 2. The bundle's CSS output (all modules' styles) gets inlined into
    // every page, as Gatsby did.
    const raw_css = await readFile(path.join(ssr, 'render.css'), 'utf8');
    const css = (await esbuild.transform(raw_css, {
        loader: 'css',
        minify: true,
        target: BROWSER_TARGET,
    })).code.trim();

    // 3. Client scripts: the touch-device player swap for work pages and
    // the 🔀-link randomizer, which every page loads for its nav links.
    await esbuild.build({
        entryPoints: [
            path.join(root, 'src', 'client', 'work.js'),
            path.join(root, 'src', 'client', 'shuffle.js'),
        ],
        bundle: true,
        minify: true,
        target: BROWSER_TARGET,
        define: {
            TABLE_MOBILE: script_json(CLASS_NAMES.tableMobile),
            PLAY_ICON: script_json(CLASS_NAMES.playIcon),
            PLAY_EVENT: script_json(GC_PLAY_EVENT),
        },
        outdir: path.join(dist, 'js'),
    });

    // 4. The redirect pages, kept as entry points for typed and bookmarked
    // URLs; in-site 🔀 clicks never come here. Thin on purpose: no layout,
    // no stylesheet, script inlined so the redirect fires during parse -- and
    // no analytics tag either: fetching count.js to count a page that replaces
    // itself in the same tick would slow down the only thing these do, and the
    // page they land on counts the visit a moment later anyway.
    const targets = random_targets();
    const redirects = [
        { path: '/random', title: 'Random Quartet', slugs: targets['random'] },
        { path: '/random-composer', title: 'Random Composer', slugs: targets['random-composer'] },
    ];
    for (const r of redirects){
        const html = '<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"/>'
            + `<title>${r.title} | ${SITE_TITLE}</title>`
            + `<script>var t=${script_json(r.slugs)};location.replace(t[Math.floor(Math.random()*t.length)]);</script>`
            + '</head><body></body></html>';
        const dir = path.join(dist, ...r.path.split('/').filter(Boolean));
        await mkdir(dir, { recursive: true });
        await writeFile(path.join(dir, 'index.html'), html);
    }

    // 5. Render every page. The nav's 🔀 links put data-shuffle on every
    // page, so every page loads shuffle.js.
    const pages = render_pages();
    for (const page of pages){
        let scripts = '<script src="/js/shuffle.js"></script>';
        if (page.component === 'work'){
            scripts += '<script src="/js/work.js"></script>';
        }
        const dir = path.join(dist, ...page.path.split('/').filter(Boolean));
        // page paths come from data.json names/catalogs; never write outside dist/
        if (!(dir + path.sep).startsWith(dist + path.sep)){
            throw new Error(`page path escapes dist/: ${page.path}`);
        }
        await mkdir(dir, { recursive: true });
        const html = page_html({ ...page, scripts }, css, app, analytics);
        await writeFile(path.join(dir, 'index.html'), html);
        if (page.path === '/404/'){
            await writeFile(path.join(dist, '404.html'), html); // Netlify's custom 404
        }
    }

    // 6. Sitemap: every rendered page except /404/, at the same URL as
    // gatsby-plugin-sitemap. The redirect pages are deliberately absent —
    // they exist to be typed and bookmarked, not to be indexed as blanks.
    const sitemap = sitemap_xml(SITE_URL, pages.map(p => p.path).filter(p => p !== '/404/'));
    await mkdir(path.join(dist, 'sitemap'), { recursive: true });
    for (const [name, xml] of Object.entries(sitemap)){
        await writeFile(path.join(dist, 'sitemap', name), xml);
    }

    // 7. Static assets, copied through as-is -- but the share cards get their
    // size checked on the way past.
    const card_count = await check_og_cards(path.join(root, 'static', 'og'));
    await cp(path.join(root, 'static'), dist, {
        recursive: true,
        filter: src => path.basename(src) !== '.DS_Store',
    });

    await rm(ssr, { recursive: true, force: true });
    console.log(`built ${pages.length + redirects.length} pages to dist/`
        + ` (${card_count} share cards under ${OG_MAX_BYTES.toLocaleString()} bytes)`);
}

await build();
